In [3]:
import pandas as pd
import numpy as np

df= pd.read_csv("Messy_Employee_dataset.csv")

df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [5]:
df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["Age"]= df["Age"].fillna(df["Age"].median())
df["Salary"]=df["Salary"].fillna(df["Salary"].median())

df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [ ]:
df["Join_Date"]= pd.to_datetime(df["Join_Date"],errors = "coerce")
df["Join_Date"].head()

0   2021-04-02
1   2020-07-10
2   2023-12-07
3   2021-11-27
4   2022-01-05
Name: Join_Date, dtype: datetime64[ns]

In [10]:
df["Phone"]= df["Phone"].astype(str).str.replace(r"\D", "",regex = True)
df["Phone"].head(10)

0    1651623197
1    1898471390
2    5596363211
3    3476490784
4    1586734256
5    5409003485
6    4518376063
7    4134327559
8    4177656123
9    8156985699
Name: Phone, dtype: object

In [11]:
df.dtypes

Employee_ID                  object
First_Name                   object
Last_Name                    object
Age                         float64
Department_Region            object
Status                       object
Join_Date            datetime64[ns]
Salary                      float64
Email                        object
Phone                        object
Performance_Score            object
Remote_Work                    bool
dtype: object

In [14]:
text_columns = ["First_Name","Last_Name","Department_Region","Status"]
for col in text_columns:
    df[col]=df[col].str.strip().str.title()

df[text_columns].head()

  First_Name Last_Name   Department_Region    Status
0        Bob     Davis   Devops-California    Active
1        Bob     Brown       Finance-Texas    Active
2      Alice     Jones        Admin-Nevada   Pending
3        Eva     Davis        Admin-Nevada  Inactive
4      Frank  Williams  Cloud Tech-Florida    Active

In [15]:
df["Status"].value_counts()

Status
Pending     356
Active      352
Inactive    312
Name: count, dtype: int64

In [16]:
df["Department_Region"].value_counts()

Department_Region
Hr-Florida               41
Devops-California        35
Sales-Nevada             35
Admin-Nevada             34
Admin-California         34
Devops-Florida           34
Finance-Illinois         33
Devops-New York          33
Sales-Florida            33
Hr-New York              33
Devops-Illinois          33
Finance-California       32
Sales-California         31
Sales-Illinois           30
Admin-Illinois           29
Finance-Texas            29
Cloud Tech-Texas         29
Cloud Tech-California    29
Finance-Nevada           29
Cloud Tech-Florida       28
Devops-Nevada            27
Devops-Texas             27
Sales-New York           26
Hr-California            26
Admin-Florida            25
Cloud Tech-New York      24
Finance-Florida          24
Hr-Illinois              24
Hr-Nevada                24
Hr-Texas                 23
Finance-New York         23
Sales-Texas              23
Admin-Texas              22
Admin-New York           22
Cloud Tech-Nevada        20
Cloud Tech-Illinois      16
Name: count, dtype: int64

In [17]:
df["Performance_Score"].value_counts()

Performance_Score
Good         270
Average      267
Excellent    267
Poor         216
Name: count, dtype: int64

In [18]:
df["Remote_Work"].value_counts()

Remote_Work
True     513
False    507
Name: count, dtype: int64

In [19]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [22]:
df["Age"]= df["Age"].astype(int)

In [23]:
df.dtypes

Employee_ID                  object
First_Name                   object
Last_Name                    object
Age                           int64
Department_Region            object
Status                       object
Join_Date            datetime64[ns]
Salary                      float64
Email                        object
Phone                        object
Performance_Score            object
Remote_Work                    bool
dtype: object

In [24]:
df["Age"].describe()

count    1020.000000
mean       31.970588
std         5.136901
min        25.000000
25%        30.000000
50%        30.000000
75%        35.000000
max        40.000000
Name: Age, dtype: float64

In [25]:
df['Salary'].describe()

count      1020.000000
mean      85164.299069
std       19638.385740
min       50047.320000
25%       68811.232500
50%       85547.870000
75%      100372.662500
max      119971.650000
Name: Salary, dtype: float64

In [ ]:
df["Join_Date"].head()